### ISSUE TITLE
RoleBinding med fulle rettigheter i namespacet for service account

### ISSUE THREAD

**Issue by linemos** [nais/deploy#33]
Det mangler en RoleBinding i GCP som gir riktige rettigheter til service accounten i namespacet til teamet.

Forslag:
RoleBinding til ClusterRolen `cluster-admin` vil gi fulle rettigheter i namespacet og ingen utenfor.

**Comment by ambientsound** [comment]
Dette ble fikset i 418ca3a1d71b33c9d35a6d3d8ac4541116b5e0d3.
