### ISSUE TITLE
Fail-fast dersom kontrakt er feil

### ISSUE THREAD

**Issue by kgunnerud** [nais/deploy#47]
Endte med å deploye en nais.yaml fil som hadde en høyere memory requested enn limit. 
Dette feilet jo selvfølgelig, men github actions sto der som pending til den fikk timeout.
Hadde det vært mulig for noe type fail-fast på slike feil?

Link til feil ligger på slack, usikker på om man kan poste de her? 🤔 
https://nav-it.slack.com/archives/CL3G3HZ37/p1575710401158600?thread_ts=1575704500.157800&cid=CL3G3HZ37

**Comment by ambientsound** [comment]
Har lagt inn støtte i NAIS deploy for å gjenkjenne feil som kun trigges i Naiserator. Dette lar oss kjenne igjen denne typen feil. Det begrenser seg til feil som kan gjenkjennes av Naiserator: hvis appen står i CrashLoopBackOff, vil den fortsatt vente til timeout.
