### ISSUE TITLE
Push av Docker image dokumentert som en del av byggetrinnet

### ISSUE THREAD

**Issue by ahusby** [nais/deploy#48]
I README.md er push av image til Dockerhub tegnet inn som en del av byggetrinnet, ikke som en del av deploy.trinnet.
1) Hva med https://github.com/nais/deploy/issues/25?
2) Er dette bare en upresis dokumentering eller er det slik bygging foregår?
3) I det siste tilfellet, stemmer det at 
> Nav betaler for kapasitet på Circleci/Github Actions og Github Package Registry. Hvis du bruker 30 sekunder i hvert bygg for å pushe docker images så koster dette. Vi betaler pr machine hour på Circleci/Github Actions. Github Package Registry tar fulle images, det betyr at der pusher du hele imaget til Github hver gang. Sist mnd brukte vi opp båndbredden mot Github Package Registry. For dockerhub er ikke dette ett gigaproblem enda, de lagrer kun differ, dessuten tror jeg de henter inn penger andre steder.

**Comment by Kyrremann** [comment]
Kunne du formatert teksten din litt bedre? Den er ganske tungvindt å lese slik som den er nå.

Vil nok kalle det mer et eksempel, som nok kunne blitt skrevet litt om til å dele opp hvor man bygger image. Er uansett ikke et krav om at du skal følge det ene eller den andre.

Ang. betaling så ville jeg nok fokusert mer mot utviklerene/teams. Tungvindt for oss i plattformteamet å bygge opp denne kulturen.

**Comment by ahusby** [comment]
>Ang. betaling så ville jeg nok fokusert mer mot utviklerene/teams. Tungvindt for oss i plattformteamet å bygge opp denne kulturen.
Betyr det at Nav sparer penger - så mye at det spiler noen rolle - ved å utsette pushing av Docker image til deploy-trinnet? Spør fordi jeg har hørt argumentet "det er ikke noe problem i praksis, så da gjør vi bare det som er enklest å implementere".

**Comment by jhrv** [comment]
dette er by design
