### ISSUE TITLE
Skriv ut payload før validering i GHA deploy, ikke etter

### ISSUE THREAD

**Issue by janolaveide** [nais/deploy#50]
Ved feil i payload i den nye deploy-mekanismen i GHA skrives bare en noe kryptisk  feilmelding ut, selv med **PRINT_PAYLOAD true**
`##[error]fatal: naiserator.yml: yaml: line 130: did not find expected key
`
Særlig ved bruk av templating er det vanskelig å se hvor denne linjen er. I CircleCI-orben ble payload skrevet ut tidligere, før vaidering, og det var lett å se hva som var feil,  det samme bør gjøres her.

**Comment by jhrv** [comment]
Fixed https://github.com/nais/deploy/commit/ea5717d316a50ec584f415590030b5019a6fea36
