### ISSUE TITLE
nais/deploy mangler --rawresources

### ISSUE THREAD

**Issue by Kyrremann** [nais/deploy#51]
Er nyttig for å unngå escaping (da kan filene også applyes manuelt), og det går det enklere å migrere.

**Comment by ambientsound** [comment]
Vil argumentere for at folk i stedet kan benytte seg av `--resources` uten å sette template-variabler. Da vil ressursene brukes as-is. Hvis man har flere kombinasjoner kan man f.eks gjøre template rendering i et tidligere steg:

```
deploy --print-payload --dry-run --resource use-templating.yml --vars vars.yml | jq .resources > templated.json
deploy --apikey ... --resource no-templating.yml --resource templated.json
```

**Comment by ambientsound** [comment]
Man kan muligens legge dette inn i action sånn at det går an for de som ikke kjører verktøyet manuelt.

**Comment by ambientsound** [comment]
wontfix pga. ingen etterspørsel.
