### ISSUE TITLE
Support parallel deployments to same cluster

### ISSUE THREAD

**Issue by tronghn** [nais/deploy#54]
Currently, deployment events to the GitHub Deployments API are sent using only the intended `cluster` as `environment` parameter. This works fine for teams only having single instances in each cluster, however results in two issues when attempting parallel deployments to the same cluster, that is, with different namespaces:

1. The GitHub API receives two, parallel deployments to the same environment. Whichever deployment has its state set to `success` last will cause "all prior, non-transient and non-production environment deploys" to be set to `inactive` (as per https://developer.github.com/v3/repos/deployments/#inactive-deployments). 
This results in a state where the first deployment is seen as `inactive` which again results in the failure of the workflow as seen here: https://github.com/navikt/veiledearbeidssoker/runs/393003136

2. The information shown in the GitHub deployments do not reflect the actual state of the deployments within the cluster, i.e. only the latest deployment to the cluster is shown as active even though multiple instances within the cluster are active (https://github.com/navikt/veiledearbeidssoker/deployments).

Proposed solution:
Append namespace to the environment property whenever a deployment contains a namespace other than `default`, e.g. `dev-fss-q1`

**Comment by ambientsound** [comment]
Other proposed solution: use something other than GitHub to retain state?
