### ISSUE TITLE
Action loggen viser flere poder enn de som blir deployet

### ISSUE THREAD

**Issue by Kyrremann** [nais/deploy#91]
Når man ser på loggen for en deployment så får man også med poder som ikke er en del av nåværende deployment. Det kan være ganske forvirrende.

```
[2022-11-06T23:40:56.787409667Z] Status: in_progress: Pod/vaktor-plan-7f9874dc75-zflvg (Unhealthy): Readiness probe failed: Get "http://10.7.81.29:4191/ready": dial tcp 10.7.81.29:4191: connect: connection refused
[2022-11-06T23:40:57.549581428Z] Status: in_progress: Pod/vaktor-plan-757cb4d4f9-cghjv (Pulling): Pulling image "ghcr.io/navikt/vaktor-plan-backend/vaktor-plan-api:b6276559abc095d2668f089be55a19c7cdd9f83d"
```

Her var det en deployment som feilet, og når man deployet en ny versjon så fikk man pods fra den gamle deploymenten i loggen. Her burde vi ta høyde for `replicaset` i stedet.

Github Action: https://github.com/navikt/vaktor-plan-backend/actions/runs/3406487347/jobs/5665220726

**Comment by sechmann** [comment]
adding prerequisites:
nais/naiserator@ac78e3bcdd3cca31b2bfa81f9e98ebdd19fe3fb8
nais/naiserator@94602ccd253671313fc9146ffcdcfb7d69057a30

**Comment by sechmann** [comment]
fixed 2806f616533fb61880d7d3cf7e8c7634cb75d1b2

**Comment by sechmann** [comment]
Dette trigger jo restart av alle podder, selv med en deploy uten noen endringer - og det er et pattern som er tatt i bruk omkring, at de deployer vel vitende om at det ikke endrer poddene, og derfor ikke blir en redeploy.

**Comment by sechmann** [comment]
Jeg kommer ikke på noen andre måter å løse dette på enn masse grisete state, venting, og ekstra kall mot apiserveren. I tillegg kom jeg på at de poddene som skrus av, som følge av deployen, er jo i høyeste gad relevante for gitt depoy.
Da tenker jeg dette fort ble en wontfix, med mindre noen har noen veldig gode forslag / motargumenter.
